name: Auto Check-in

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  task:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Daily check-in
        run: python check_in.py
        env:
          JUEJIN_SESSION_ID: ${{ secrets.JUEJIN_SESSION_ID }}
