name: Auto Check-in

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'  # timezone: UTC

jobs:
  task:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f package.json ]; then npm install; fi

      - name: Daily check-in
        run: python check_in.py
        env:
          JUEJIN_SESSION_ID: ${{ secrets.JUEJIN_SESSION_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

      - name: Auto play HaiDiJuejin
        run: node auto-game.js
        env:
          JUEJIN_SESSION_ID: ${{ secrets.JUEJIN_SESSION_ID }}
